basePath: /api/web/v1
host: localhost:8080
info:
  contact: {}
  description: A scalable, high-performance, and high-availability web application
    template built with Go.
  title: Web API
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    description: Bearer token authentication
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
