apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  namespace: go-layout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task
        image: ${REGISTRY}/go-layout-task:${TAG}
        imagePullPolicy: Always
        env:
        - name: GO_ENV
          valueFrom:
            configMapKeyRef:
              name: go-layout-config
              key: GO_ENV
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: go-layout-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: go-layout-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: go-layout-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: go-layout-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: go-layout-config
              key: DB_NAME
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: go-layout-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: go-layout-config
              key: REDIS_PORT
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: go-layout-config
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: go-layout-config
              key: RABBITMQ_PORT
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
